[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "solmate/=lib/solmate/src/",
    "forge-std/=lib/forge-std/src/"
]


[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }